import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, AlertTriangle, CheckCircle2, ChevronRight, ShieldCheck, Zap} from 'lucide-react';
import {Area, AreaChart, Bar, CartesianGrid, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import './styles.css';
type Account={account_id:string;account_name:string;archetype:string;telemetry:any[]};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function Card({label,value,detail,kind='indigo'}:{label:string,value:string,detail:string,kind?:string}){return <section className="kpi"><span>{label}</span><b>{value}</b><small className={kind}>{detail}</small></section>}
function App(){const [accounts,setAccounts]=useState<Account[]>([]);const [demo,setDemo]=useState<any>();const [selected,setSelected]=useState('acct_001');const [persona,setPersona]=useState(1);
 useEffect(()=>{Promise.all([fetch('/api/telemetry').then(r=>r.json()),fetch('/api/demo').then(r=>r.json())]).then(([a,d])=>{setAccounts(a);setDemo(d)})},[]);
 const account=accounts.find(a=>a.account_id===selected);const trace=useMemo(()=>account?.telemetry.filter((_:any,i:number)=>i%5===0).map((x:any)=>({...x,date:x.timestamp.slice(5,10),events:x.feature_events_daily.api_calls+x.feature_events_daily.webhooks}))||[],[account]);
 if(!demo||!account)return <main className="loading">Initializing Swarm Ops Control Center…</main>; const gap=demo.gap; const isGrifter=persona===1;
 return <main><header><div><p className="eyebrow"><Zap size={14}/> DUAL-LOOP RETENTION SWARM</p><h1>Swarm Ops Control Center</h1></div><div className="live"><i/> LIVE · deterministic run</div></header>
 <section className="agents">{[['Value Realization Agent','Healthy · Monitoring 10 accounts','emerald'],['Exploit Auditor Agent','Active · 2 vulnerabilities mitigated','rose'],['Policy Synthesizer','Idle · Auto-Patching Enabled','amber']].map(([a,b,c])=><div className="agent" key={a}><Activity size={16} className={c}/><div><b>{a}</b><small>{b}</small></div><CheckCircle2 size={16} className="emerald"/></div>)}</section>
 <section className="kpis"><Card label="Portfolio MASR" value="91.4%" detail="↑ 11.4% recovered" kind="emerald"/><Card label="Exposure Mitigated" value="$144,000" detail="annualized margin protected" kind="emerald"/><Card label="Autonomous Patches" value="2 / 0" detail="deployed / escalated"/><Card label="At-Risk MRR" value="$27,800" detail="10 accounts in evaluation" kind="amber"/></section>
 <section className="grid charts"><article className="panel chart"><div className="panel-head"><div><p className="eyebrow">ACCOUNT TELEMETRY</p><h2>{account.account_name} <span>· {account.account_id}</span></h2></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.account_id} — {a.account_name}</option>)}</select></div><ResponsiveContainer width="100%" height={285}><ComposedChart data={trace}><CartesianGrid stroke="#263349" vertical={false}/><XAxis dataKey="date" tick={{fill:'#8292ae',fontSize:11}}/><YAxis yAxisId="seats" tick={{fill:'#8292ae',fontSize:11}}/><YAxis yAxisId="events" orientation="right" tick={{fill:'#8292ae',fontSize:11}}/><Tooltip contentStyle={{background:'#111827',border:'1px solid #334155'}}/><Area yAxisId="seats" dataKey="paid_seats" fill="#3730a344" stroke="#818cf8" name="Paid seats"/><Area yAxisId="seats" dataKey="active_seats_dau" fill="#f43f5e33" stroke="#fb7185" name="Active daily seats"/><Bar yAxisId="events" dataKey="events" fill="#34d39999" name="Feature events"/></ComposedChart></ResponsiveContainer></article>
 <article className="panel diagnostic"><p className="eyebrow">ENTITLEMENT REALIZATION</p><div className="ratio">{Math.round(gap.utilization_ratio*100)}%</div><p>Utilization ratio</p><div className="tags">{gap.unused_high_value_features.map((x:string)=><span key={x}>{x}</span>)}</div><div className="roi"><b>{money(Number(gap.roi_gap_usd_monthly))}/mo</b><small>estimated ROI gap</small></div><p className="muted">{gap.narrative}</p></article></section>
 <section className="inspector"><div className="title"><ShieldCheck/> Closed-Loop Remediation Inspector <span>same persona · policy v1 → v2</span></div><div className="diff"><article className="baseline"><p className="eyebrow">EXPLOITED BASELINE</p><code>{demo.before_offer.rule_id}</code><h3 className="danger">{demo.before_offer.text}</h3><div className="alert"><AlertTriangle size={18}/><b>CRITICAL · uncapped_discount</b><small>$1,800 LTV erosion · $72,000 annualized exposure</small></div><b>MASR baseline <strong>0.8000</strong></b></article><div className="arrow"><ChevronRight/></div><article className="patch"><p className="eyebrow">AUTONOMOUS POLICY PATCH</p>{demo.patch.operations.map((o:any)=><div className="op" key={o.op}><code>{o.op}</code><b>→ {String(o.value)}{o.op==='shorten_duration'?' mo':o.op==='extend_cooldown'?' days':''}</b></div>)}<span className="approved"><CheckCircle2 size={14}/> Auto-applied · no approval required</span></article><div className="arrow"><ChevronRight/></div><article className="recovered"><p className="eyebrow">REMEDIATED OFFER</p><h3 className="success">{demo.after_offer.text}</h3><b>MASR post-patch <strong>0.9500</strong></b><p className="emerald">+0.1500 recovery</p><small>−2% save rate for +18.75% margin efficiency</small></article></div></section>
 <section className="panel sandbox"><div><p className="eyebrow">INTERACTIVE REPLAY SANDBOX</p><h2>Adversarial persona simulation</h2></div><input type="range" min="0" max="2" value={persona} onChange={e=>setPersona(+e.target.value)}/><div className="persona"><b>{['Price-Sensitive Churner','Discount Grifter','Value-Confused Admin'][persona]}</b><span>{isGrifter?'Discount farming rejected → workflow consultation':'Policy routes to rightsizing or onboarding consultation'}</span></div></section>
 </main>};createRoot(document.getElementById('root')!).render(<App/>);
