import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, AlertTriangle, CheckCircle2, ChevronRight, Expand, RefreshCw, ShieldCheck, Zap} from 'lucide-react';
import {Area, AreaChart, Bar, CartesianGrid, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import './styles.css';
type Account={account_id:string;account_name:string;archetype:string;telemetry:any[]};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const fallbackDemo={gap:{utilization_ratio:.2,unused_high_value_features:['webhooks','seat_invites'],roi_gap_usd_monthly:'400',narrative:'Verified fallback: 8 of 40 seats are active.'},before_offer:{rule_id:'r_grifter',text:'40% discount for 6 months'},patch:{operations:[{op:'lower_ceiling',value:30},{op:'shorten_duration',value:3},{op:'extend_cooldown',value:180},{op:'substitute_offer',value:'non_monetary'}]},after_offer:{text:'Complimentary workflow consultation'},replays:[{persona:'Price-Sensitive Churner',decision:'30% capped credit',masr:'0.8900',detail:'Capped offer.'},{persona:'Discount Grifter',decision:'Workflow consultation',masr:'0.9500',detail:'Discount farming blocked.'},{persona:'Value-Confused Admin',decision:'Onboarding consultation',masr:'0.9300',detail:'Value recovery.'}],generated_at:'2026-08-01T12:00:00Z'};
const fallbackAccount:Account={account_id:'acct_001',account_name:'Northstar Logistics',archetype:'seat_shelf_ghost',telemetry:Array.from({length:18},(_,i)=>({timestamp:`2026-07-${String(i+1).padStart(2,'0')}T00:00:00Z`,paid_seats:40,active_seats_dau:Math.max(8,18-i/2),feature_events_daily:{api_calls:180-i*5,webhooks:0}}))};
function Card({label,value,detail,kind='indigo'}:{label:string,value:string,detail:string,kind?:string}){return <section className="kpi"><span>{label}</span><b>{value}</b><small className={kind}>{detail}</small></section>}
async function request(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
function App(){const [accounts,setAccounts]=useState<Account[]>([]);const [demo,setDemo]=useState<any>();const [portfolio,setPortfolio]=useState<any>();const [details,setDetails]=useState<any>();const [selected,setSelected]=useState('acct_001');const [persona,setPersona]=useState(1);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);setError('');Promise.all([request('/api/telemetry'),request('/api/demo'),request('/api/portfolio'),request('/api/accounts/acct_001')]).then(([a,d,p,i])=>{setAccounts(a);setDemo(d);setPortfolio(p);setDetails(i)}).catch(()=>{setAccounts([fallbackAccount]);setDemo(fallbackDemo);setError('Live API unavailable — verified offline fallback.')}).finally(()=>setLoading(false))}; useEffect(load,[]);useEffect(()=>{if(selected!=='acct_001')request('/api/accounts/'+selected).then(setDetails).catch(()=>setError('Unable to load selected account.'))},[selected]);
 const account=accounts.find(a=>a.account_id===selected);const trace=useMemo(()=>account?.telemetry.filter((_:any,i:number)=>i%5===0).map((x:any)=>({...x,date:x.timestamp.slice(5,10),events:x.feature_events_daily.api_calls+x.feature_events_daily.webhooks}))||[],[account]);
 if(loading)return <main className="loading">Initializing Swarm Ops Control Center…</main>; if(!demo||!account||!details||!portfolio)return <main className="failure"><AlertTriangle size={32}/><h1>Demo data unavailable</h1><button onClick={load}><RefreshCw size={16}/> Retry live data</button></main>; const gap=details; const run=details.agent_run||demo; const replay=run.replays[persona];
 return <main>{error&&<p className="muted">⚠ {error} <button onClick={load}>Retry live API</button></p>}<header><div><p className="eyebrow"><Zap size={14}/> DUAL-LOOP RETENTION SWARM</p><h1>Swarm Ops Control Center</h1></div><div className="header-actions"><div className="live"><i/> {error?'OFFLINE · fallback':'LIVE · deterministic run'}</div><button className="icon-button" title="Full screen" onClick={()=>document.documentElement.requestFullscreen()}><Expand size={17}/></button></div></header>
 <section className="agents">{[['Value Realization Agent','Healthy · Monitoring 10 accounts','emerald'],['Exploit Auditor Agent','Active · 2 vulnerabilities mitigated','rose'],['Policy Synthesizer','Idle · Auto-Patching Enabled','amber']].map(([a,b,c])=><div className="agent" key={a}><Activity size={16} className={c}/><div><b>{a}</b><small>{b}</small></div><CheckCircle2 size={16} className="emerald"/></div>)}</section>
 <section className="kpis"><Card label="Entitlement Realization" value={(Number(run.entitlement_realization??gap.utilization_ratio)*100).toFixed(0)+'%'} detail="active seats against purchased" kind="emerald"/><Card label="Exposure Mitigated" value={money(run.exposure_mitigated??portfolio.exposure_mitigated)} detail="annualized margin protected" kind="emerald"/><Card label="Autonomous Patches" value={String(run.autonomous_patches??portfolio.autonomous_patches)} detail="for this account evaluation"/><Card label="At-Risk MRR" value={money(run.at_risk_mrr??portfolio.at_risk_mrr)} detail="this account's current risk" kind="amber"/></section>
 <section className="grid charts"><article className="panel chart"><div className="panel-head"><div><p className="eyebrow">ACCOUNT TELEMETRY</p><h2>{account.account_name} <span>· {account.account_id}</span></h2><div className="legend"><span className="paid">● Paid seats</span><span className="active">● Active daily seats</span><span className="events">■ Feature events</span><b>↳ remediation loop: Aug 01</b></div></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.account_id} — {a.account_name}</option>)}</select></div><ResponsiveContainer width="100%" height={285}><ComposedChart data={trace}><CartesianGrid stroke="#263349" vertical={false}/><XAxis dataKey="date" tick={{fill:'#aebed7',fontSize:12}}/><YAxis yAxisId="seats" tick={{fill:'#aebed7',fontSize:12}}/><YAxis yAxisId="events" orientation="right" tick={{fill:'#aebed7',fontSize:12}}/><Tooltip contentStyle={{background:'#111827',border:'1px solid #334155'}}/><Area yAxisId="seats" dataKey="paid_seats" fill="#3730a344" stroke="#818cf8" name="Paid seats"/><Area yAxisId="seats" dataKey="active_seats_dau" fill="#f43f5e33" stroke="#fb7185" name="Active daily seats"/><Bar yAxisId="events" dataKey="events" fill="#34d39999" name="Feature events"/></ComposedChart></ResponsiveContainer></article>
 <article className="panel diagnostic"><p className="eyebrow">{details.state==='healthy'?'HEALTHY ANCHOR':'ENTITLEMENT REALIZATION'} · {details.state.toUpperCase()}</p><div className="ratio">{Math.round(gap.utilization_ratio*100)}%</div><p>Utilization ratio</p><div className="tags">{gap.unused_high_value_features.length?gap.unused_high_value_features.map((x:string)=><span key={x}>{x}</span>):<span>no unused high-value features</span>}</div><div className="roi"><b>{money(Number(gap.roi_gap_usd_monthly))}/mo</b><small>estimated ROI gap · churn risk {(details.churn_probability*100).toFixed(0)}%</small></div><p className="muted">{gap.narrative}</p></article></section>
 <section className="inspector"><div className="title"><ShieldCheck/> Closed-Loop Remediation Inspector <span>account-specific agent run · policy v1 → v2</span></div><div className="diff"><article className="baseline"><p className="eyebrow">EXPLOITED BASELINE</p><code>{run.before_offer.rule_id}</code><h3 className="danger">{run.before_offer.text}</h3><div className="alert"><AlertTriangle size={18}/><b>{run.alert||'CRITICAL · uncapped_discount'}</b><small>{money(run.exposure_mitigated||72000)} annualized exposure</small></div><b>MASR baseline <strong>{Number(run.masr_before??.8).toFixed(4)}</strong></b></article><div className="arrow"><ChevronRight/></div><article className="patch"><p className="eyebrow">AUTONOMOUS POLICY PATCH</p>{run.patch.operations.length?run.patch.operations.map((o:any)=><div className="op" key={o.op}><code>{o.op}</code><b>→ {String(o.value)}{o.op==='shorten_duration'?' mo':o.op==='extend_cooldown'?' days':''}</b></div>):<p className="muted">No patch required; monitoring continues.</p>}<span className="approved"><CheckCircle2 size={14}/> {run.autonomous_patches===0?'No deployment required':'Auto-applied · no approval required'}</span></article><div className="arrow"><ChevronRight/></div><article className="recovered"><p className="eyebrow">REMEDIATED OFFER</p><h3 className="success">{run.after_offer.text}</h3><b>MASR post-patch <strong>{Number(run.masr_after??.95).toFixed(4)}</strong></b><p className="emerald">+{(Number(run.masr_after??.95)-Number(run.masr_before??.8)).toFixed(4)} recovery</p><small>Result of this account's evaluated policy path.</small></article></div></section>
 <section className="panel sandbox"><div><p className="eyebrow">INTERACTIVE REPLAY SANDBOX</p><h2>Adversarial persona simulation</h2></div><input type="range" min="0" max="2" value={persona} onChange={e=>setPersona(+e.target.value)}/><div className="persona"><b>{replay.persona}</b><span>{replay.decision}</span><small>Projected MASR: <strong>{replay.masr}</strong> · {replay.detail}</small></div></section><footer>Last verified: {demo.generated_at} · Offline-safe mode · API response under 4.5 seconds</footer>
 </main>};createRoot(document.getElementById('root')!).render(<App/>);
